platform :ios, '9.0'

source 'https://gitlab+deploy-token-3:uKaSsz4E1Xar-icLsuY4@gitlabdev.paciolan.info/development/application/integration/mobile/msdk-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'SdkApp_Example' do
  pod 'SdkApp', :path => '../'

  target 'SdkApp_Tests' do
    inherit! :search_paths
  end
end
